sudo: false
language: android

jdk:
    - oraclejdk8

env:
  secure: "sL4J3mCIuh5hs7sOsBdEjf9Sc0OLmMjtZFsyKU67KU83NBjTHNRr5Gv++q3kutzX1K2Ov/NTp3t9J72XKtWgCwO0ueQLmIMhe2z1aTLuKnscXiWgTgER9CzlO5pHUlZgFkM5r5Ug1Q45T5Kyv9BMQIbZ0tcjI2OpJmCU+ukBVnZSCcNsfkuXXeNCW8oiFjrYuA4a2ababw/D/bE8SkXfvscImgLZMji8JAUdhXyXZRim7r1RVHPW0GEfs0WjxF4Vta4RRndn+lq9fXqTTr+uiToTRx5Y7Ou2ULm306gZtKcxpuISc5yRB6zYRfx7/DCeoNbCYlxIx83MuxjkhggZLUldUh4mospc/+Dqoar4qHyGB0LwOtWAqPALgZe+tq+Zin0TyqtK1skZeR/t1OUt1R6Oiv2Mjycep840Xkj1PTIoUjslUILlrvZQ1pmSXDXQbrNXdlZvNWYTI/IAwQ6sMI4OAGh5dX3IQLOGytqyHk1qZt7jmVpHCdQVbpEKoSUytGkip4BeoRQKI/y8IhapA5wecWa4m58sobFVzr6TatH4sfXW8Jj5ZdRVrnEjpyLmkVBbtyq/zLphJPZLl5UCLMb4/qdl19lbK38SZ1TuczB44WJ3BDmtHjuq1rwW1J7MDNREPqjyX+XdDWmD7EAPNJuo9vnYgp02TJ6tDW0VEd0="

android:
  components:
    - build-tools-23.0.0
    - android-16
    - android-19
    - android-21
    - android-22
    - android-23
    - extra-google-m2repository
    - extra-android-m2repository
    - extra-google-google_play_services

before_install:
 - gradle -v

script:
 - gradle :app:test
